-- =========================================================================
-- AgendaLab — Interdições de salas e equipamentos por período
-- Execute depois de supabase/sql/prevencao_concorrencia.sql.
-- Depois deste arquivo, execute migracao_cancelamento_reservas_manutencao.sql.
-- =========================================================================

-- 1) Entidade temporal de manutenção
create table if not exists public.bloqueios_manutencao (
  id bigint generated by default as identity primary key,
  id_sala bigint references public.salas(id_sala) on delete cascade,
  id_equipamento bigint references public.equipamentos(id) on delete cascade,
  id_adm bigint references public.administradores(id_adm) on delete set null,
  inicio timestamptz not null,
  fim timestamptz not null,
  motivo text not null,
  criado_em timestamptz not null default now(),
  constraint bloqueios_manutencao_recurso_check
    check (num_nonnulls(id_sala, id_equipamento) = 1),
  constraint bloqueios_manutencao_periodo_check
    check (fim > inicio),
  constraint bloqueios_manutencao_motivo_check
    check (char_length(btrim(motivo)) between 1 and 500)
);

create index if not exists bloqueios_manutencao_sala_periodo_idx
  on public.bloqueios_manutencao (id_sala, inicio, fim)
  where id_sala is not null;

create index if not exists bloqueios_manutencao_equipamento_periodo_idx
  on public.bloqueios_manutencao (id_equipamento, inicio, fim)
  where id_equipamento is not null;

comment on table public.bloqueios_manutencao is
  'Faixas de data/hora nas quais uma sala ou equipamento está interditado para manutenção.';

-- 2) Leitura pública para que o calendário possa exibir período e justificativa.
-- Escrita restrita ao administrador autenticado e identificado em id_adm.
alter table public.bloqueios_manutencao enable row level security;

drop policy if exists bloqueios_manutencao_select on public.bloqueios_manutencao;
create policy bloqueios_manutencao_select
  on public.bloqueios_manutencao
  for select
  to anon, authenticated
  using (true);

drop policy if exists bloqueios_manutencao_insert on public.bloqueios_manutencao;
create policy bloqueios_manutencao_insert
  on public.bloqueios_manutencao
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.administradores administrador
      where administrador.uuid = (select auth.uid())
        and administrador.id_adm = bloqueios_manutencao.id_adm
    )
  );

drop policy if exists bloqueios_manutencao_update on public.bloqueios_manutencao;
create policy bloqueios_manutencao_update
  on public.bloqueios_manutencao
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.administradores administrador
      where administrador.uuid = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from public.administradores administrador
      where administrador.uuid = (select auth.uid())
        and administrador.id_adm = bloqueios_manutencao.id_adm
    )
  );

drop policy if exists bloqueios_manutencao_delete on public.bloqueios_manutencao;
create policy bloqueios_manutencao_delete
  on public.bloqueios_manutencao
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.administradores administrador
      where administrador.uuid = (select auth.uid())
    )
  );

grant select on table public.bloqueios_manutencao to anon, authenticated;
grant insert, update, delete on table public.bloqueios_manutencao to authenticated;
grant usage, select on sequence public.bloqueios_manutencao_id_seq to authenticated;

-- 3) O mesmo lock usado pelas reservas serializa uma nova interdição com
-- solicitações simultâneas do mesmo recurso.
create or replace function public.preparar_bloqueio_manutencao()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  NEW.motivo := btrim(NEW.motivo);

  if NEW.fim <= NEW.inicio then
    raise exception 'O fim da interdição deve ser posterior ao início.';
  end if;

  if NEW.id_sala is not null then
    perform 1
    from public.salas
    where id_sala = NEW.id_sala
    for update;

    if not found then
      raise exception 'Sala não encontrada.';
    end if;
  else
    perform 1
    from public.equipamentos
    where id = NEW.id_equipamento
    for update;

    if not found then
      raise exception 'Equipamento não encontrado.';
    end if;
  end if;

  return NEW;
end;
$$;

drop trigger if exists trg_preparar_bloqueio_manutencao on public.bloqueios_manutencao;
create trigger trg_preparar_bloqueio_manutencao
  before insert or update on public.bloqueios_manutencao
  for each row
  execute function public.preparar_bloqueio_manutencao();

-- 4) Defesa no banco: INSERT direto, fallback do cliente e RPC passam por estas
-- triggers. Intervalos são tratados como [início, fim), permitindo blocos
-- consecutivos sem conflito na fronteira.
create or replace function public.checar_concorrencia_reserva_sala()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status public.status_recurso;
  v_motivo_manutencao text;
begin
  if NEW.status in ('pendente', 'aprovada') then
    if NEW.fim <= NEW.inicio then
      raise exception 'O fim da reserva deve ser posterior ao início.';
    end if;

    select status into v_status
    from public.salas
    where id_sala = NEW.id_sala
    for update;

    if v_status is null then
      raise exception 'Sala não encontrada.';
    end if;

    if v_status <> 'livre' then
      raise exception 'Este recurso não está disponível para reservas no momento.';
    end if;

    select motivo into v_motivo_manutencao
    from public.bloqueios_manutencao
    where id_sala = NEW.id_sala
      and tstzrange(inicio, fim, '[)') && tstzrange(NEW.inicio, NEW.fim, '[)')
    order by inicio
    limit 1;

    if v_motivo_manutencao is not null then
      raise exception 'Este recurso está em manutenção no período selecionado. Motivo: %', v_motivo_manutencao;
    end if;

    if exists (
      select 1
      from public.reservas_salas
      where id_sala = NEW.id_sala
        and status in ('pendente', 'aprovada')
        and id <> coalesce(NEW.id, 0)
        and tstzrange(inicio, fim, '[)') && tstzrange(NEW.inicio, NEW.fim, '[)')
    ) then
      raise exception 'Este horário acabou de ser reservado por outro usuário. Por favor, escolha outro período.'
        using errcode = '23P01';
    end if;
  end if;

  return NEW;
end;
$$;

create or replace function public.checar_concorrencia_reserva_equipamento()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_qtd_estoque integer;
  v_soma_uso integer;
  v_status public.status_recurso;
  v_motivo_manutencao text;
begin
  if NEW.status in ('pendente', 'aprovada') then
    if NEW.fim <= NEW.inicio then
      raise exception 'O fim da reserva deve ser posterior ao início.';
    end if;

    select quantidade, status into v_qtd_estoque, v_status
    from public.equipamentos
    where id = NEW.id_equipamento
    for update;

    if v_qtd_estoque is null then
      raise exception 'Equipamento não encontrado.';
    end if;

    if v_status <> 'livre' then
      raise exception 'Este recurso não está disponível para reservas no momento.';
    end if;

    select motivo into v_motivo_manutencao
    from public.bloqueios_manutencao
    where id_equipamento = NEW.id_equipamento
      and tstzrange(inicio, fim, '[)') && tstzrange(NEW.inicio, NEW.fim, '[)')
    order by inicio
    limit 1;

    if v_motivo_manutencao is not null then
      raise exception 'Este recurso está em manutenção no período selecionado. Motivo: %', v_motivo_manutencao;
    end if;

    select coalesce(sum(coalesce(quantidade, 1)), 0) into v_soma_uso
    from public.reservas_equipamentos
    where id_equipamento = NEW.id_equipamento
      and status in ('pendente', 'aprovada')
      and id <> coalesce(NEW.id, 0)
      and tstzrange(inicio, fim, '[)') && tstzrange(NEW.inicio, NEW.fim, '[)');

    if (v_soma_uso + coalesce(NEW.quantidade, 1)) > v_qtd_estoque then
      raise exception 'Este horário acabou de ser reservado por outro usuário. Por favor, escolha outro período.'
        using errcode = '23P01';
    end if;
  end if;

  return NEW;
end;
$$;

drop trigger if exists trg_checar_concorrencia_reserva_sala on public.reservas_salas;
create trigger trg_checar_concorrencia_reserva_sala
  before insert or update on public.reservas_salas
  for each row
  execute function public.checar_concorrencia_reserva_sala();

drop trigger if exists trg_checar_concorrencia_reserva_equipamento on public.reservas_equipamentos;
create trigger trg_checar_concorrencia_reserva_equipamento
  before insert or update on public.reservas_equipamentos
  for each row
  execute function public.checar_concorrencia_reserva_equipamento();

-- 5) Atualizações de interdição aparecem imediatamente na agenda quando a
-- publicação Realtime padrão do Supabase estiver disponível.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'bloqueios_manutencao'
    ) then
    execute 'alter publication supabase_realtime add table public.bloqueios_manutencao';
  end if;
end;
$$;
