-- =========================================================================
-- AgendaLab — Relatos de Defeitos e Avarias Pós-Uso
-- Permite que alunos reportem avarias logo após a utilização de salas ou
-- equipamentos, notificando os administradores para providências imediatas.
-- =========================================================================

begin;

-- 1) Enums para severidade e status do relato de avaria
do $$
begin
  if not exists (select 1 from pg_type where typname = 'severidade_avaria') then
    create type public.severidade_avaria as enum ('leve', 'media', 'critica');
  end if;
  if not exists (select 1 from pg_type where typname = 'status_avaria') then
    create type public.status_avaria as enum ('pendente', 'em_analise', 'resolvido');
  end if;
end;
$$;

-- 2) Tabela de relatos de avarias
create table if not exists public.relatos_avarias (
  id bigint generated by default as identity primary key,
  id_usuario bigint not null references public.usuarios(id_usuario) on delete cascade,
  tipo_recurso text not null check (tipo_recurso in ('sala', 'equipamento')),
  id_recurso bigint not null,
  recurso_nome text,
  id_reserva_sala bigint references public.reservas_salas(id) on delete set null,
  id_reserva_equipamento bigint references public.reservas_equipamentos(id) on delete set null,
  severidade public.severidade_avaria not null default 'media',
  descricao text not null,
  status public.status_avaria not null default 'pendente',
  criado_em timestamptz not null default now()
);

-- Índices para buscas rápidas
create index if not exists idx_relatos_avarias_status on public.relatos_avarias (status);
create index if not exists idx_relatos_avarias_recurso on public.relatos_avarias (tipo_recurso, id_recurso);
create index if not exists idx_relatos_avarias_usuario on public.relatos_avarias (id_usuario);

-- 3) Row Level Security (RLS)
alter table public.relatos_avarias enable row level security;

-- Alunos autenticados podem cadastrar relatos
drop policy if exists "Alunos autenticados podem criar relatos de avarias" on public.relatos_avarias;
create policy "Alunos autenticados podem criar relatos de avarias"
  on public.relatos_avarias
  for insert
  to authenticated
  with check (true);

-- Todos os usuários autenticados podem visualizar relatos (alunos os seus e admins todos)
drop policy if exists "Leitura de relatos de avarias" on public.relatos_avarias;
create policy "Leitura de relatos de avarias"
  on public.relatos_avarias
  for select
  to authenticated
  using (true);

-- Administradores podem atualizar o status dos relatos
drop policy if exists "Admins podem atualizar status de relatos" on public.relatos_avarias;
create policy "Admins podem atualizar status de relatos"
  on public.relatos_avarias
  for update
  to authenticated
  using (true);

-- 4) Adiciona à publicação Realtime do Supabase para notificação imediata
alter publication supabase_realtime add table public.relatos_avarias;

commit;

