-- Vistorias patrimoniais na entrega e no retorno de equipamentos.
-- Aplicar após acessorios_reserva_sala.sql.
begin;

create table if not exists public.vistorias_equipamentos (
  id bigint generated by default as identity primary key,
  id_reserva_equipamento bigint not null references public.reservas_equipamentos(id) on delete restrict,
  id_adm bigint references public.administradores(id_adm) on delete set null,
  etapa text not null check (etapa in ('entrega', 'devolucao')),
  cabo_presente boolean not null,
  pecas_completas boolean not null,
  sem_danos_visiveis boolean not null,
  observacoes text,
  criado_em timestamptz not null default now(),
  constraint vistorias_equipamentos_etapa_unica unique (id_reserva_equipamento, etapa),
  constraint vistorias_equipamentos_entrega_integra check (
    etapa <> 'entrega' or (cabo_presente and pecas_completas and sem_danos_visiveis)
  ),
  constraint vistorias_equipamentos_ressalva check (
    (cabo_presente and pecas_completas and sem_danos_visiveis)
    or nullif(btrim(observacoes), '') is not null
  )
);

create index if not exists vistorias_equipamentos_reserva_idx
  on public.vistorias_equipamentos (id_reserva_equipamento, criado_em);

alter table public.vistorias_equipamentos enable row level security;

drop policy if exists vistorias_equipamentos_select on public.vistorias_equipamentos;
create policy vistorias_equipamentos_select on public.vistorias_equipamentos
  for select to authenticated using (
    exists (
      select 1 from public.administradores a where a.uuid = (select auth.uid())
    ) or exists (
      select 1 from public.reservas_equipamentos r
      join public.usuarios u on u.id_usuario = r.id_usuario
      where r.id = id_reserva_equipamento and u.uuid = (select auth.uid())
    )
  );

-- Escrita somente pela RPC: uma reserva e sua vistoria mudam na mesma transação.
revoke all on public.vistorias_equipamentos from public, anon, authenticated;
grant select on public.vistorias_equipamentos to authenticated;

create or replace function public.registrar_vistoria_equipamento(
  p_id_reserva_equipamento bigint,
  p_etapa text,
  p_cabo_presente boolean,
  p_pecas_completas boolean,
  p_sem_danos_visiveis boolean,
  p_observacoes text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id_adm bigint;
  v_reserva public.reservas_equipamentos%rowtype;
begin
  select id_adm into v_id_adm
  from public.administradores
  where uuid = (select auth.uid());

  if v_id_adm is null then
    raise exception 'Apenas responsáveis pelo laboratório podem registrar vistorias.';
  end if;

  if p_etapa not in ('entrega', 'devolucao') or p_etapa is null then
    raise exception 'Etapa de vistoria inválida.';
  end if;

  select * into v_reserva
  from public.reservas_equipamentos
  where id = p_id_reserva_equipamento
  for update;

  if not found or v_reserva.status <> 'aprovada' or v_reserva.status_devolucao <> 'pendente' then
    raise exception 'A reserva não está aprovada ou já foi devolvida.';
  end if;

  if p_etapa = 'entrega' then
    if p_cabo_presente is distinct from true
       or p_pecas_completas is distinct from true
       or p_sem_danos_visiveis is distinct from true then
      raise exception 'Confirme todos os itens obrigatórios antes da entrega.';
    end if;
  elsif not exists (
    select 1 from public.vistorias_equipamentos
    where id_reserva_equipamento = p_id_reserva_equipamento and etapa = 'entrega'
  ) then
    raise exception 'Registre a vistoria de entrega antes da devolução.';
  end if;

  if p_cabo_presente is null or p_pecas_completas is null or p_sem_danos_visiveis is null then
    raise exception 'Confira todos os itens da vistoria.';
  end if;

  if (not p_cabo_presente or not p_pecas_completas or not p_sem_danos_visiveis)
     and nullif(btrim(p_observacoes), '') is null then
    raise exception 'Descreva as peças ausentes ou avarias encontradas.';
  end if;

  insert into public.vistorias_equipamentos (
    id_reserva_equipamento, id_adm, etapa, cabo_presente,
    pecas_completas, sem_danos_visiveis, observacoes
  ) values (
    p_id_reserva_equipamento, v_id_adm, p_etapa, p_cabo_presente,
    p_pecas_completas, p_sem_danos_visiveis, nullif(btrim(p_observacoes), '')
  );

  if p_etapa = 'devolucao' then
    update public.reservas_equipamentos
    set status_devolucao = 'devolvido', id_adm = v_id_adm
    where id = p_id_reserva_equipamento;
  end if;
end;
$$;

revoke all on function public.registrar_vistoria_equipamento(bigint, text, boolean, boolean, boolean, text) from public;
grant execute on function public.registrar_vistoria_equipamento(bigint, text, boolean, boolean, boolean, text) to authenticated;

-- Evita que um UPDATE direto pule a conferência de entrada.
create or replace function public.exigir_vistoria_devolucao()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status = 'aprovada'
     and new.status = 'aprovada'
     and old.status_devolucao = 'pendente'
     and new.status_devolucao = 'devolvido'
     and not exists (
       select 1 from public.vistorias_equipamentos
       where id_reserva_equipamento = new.id and etapa = 'devolucao'
     ) then
    raise exception 'Registre a vistoria antes de marcar o equipamento como devolvido.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_exigir_vistoria_devolucao on public.reservas_equipamentos;
create trigger trg_exigir_vistoria_devolucao
  before update of status_devolucao on public.reservas_equipamentos
  for each row execute function public.exigir_vistoria_devolucao();

do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    return;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'vistorias_equipamentos'
  ) then
    alter publication supabase_realtime add table public.vistorias_equipamentos;
  end if;
end;
$$;

commit;
